// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUJyvyUkqx7tFOzPrsb8crW7fn9HJrchc',
    appId: '1:470304276733:android:252a7598a67cf8d213be94',
    messagingSenderId: '470304276733',
    projectId: 'simakfresh-d5d86',
    storageBucket: 'simakfresh-d5d86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYcv8lzCknCQ43-fYYCq4QjvxnC7fj0uc',
    appId: '1:470304276733:ios:e7924bd1c85b64a313be94',
    messagingSenderId: '470304276733',
    projectId: 'simakfresh-d5d86',
    storageBucket: 'simakfresh-d5d86.firebasestorage.app',
    androidClientId: '470304276733-4tb1bevukctraknkri496ruh4pf4lo3q.apps.googleusercontent.com',
    iosClientId: '470304276733-0qdqq2hj0birdcn8l39d1j8qq1429ti6.apps.googleusercontent.com',
    iosBundleId: 'com.simakfresh.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYdgAolXjmMhmvfStttsyIO7SWtRDq2YM',
    appId: '1:470304276733:web:caf4139bebf3c8cd13be94',
    messagingSenderId: '470304276733',
    projectId: 'simakfresh-d5d86',
    authDomain: 'simakfresh-d5d86.firebaseapp.com',
    storageBucket: 'simakfresh-d5d86.firebasestorage.app',
  );

}